# Generated by Django 3.2.16 on 2023-10-30 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='date',
            field=models.DateField(blank=True, verbose_name='Дата платежа'),
        ),
    ]
